@startuml
map Unit {
  Knight=>status=1
  Swordsman=>status=2
  Pikeman=>status=3
}
object Swordsman{
status=2
}
Unit::Knight --> Swordsman : Eliminates
object Pikeman{
status=3
}
Unit::Swordsman --> Pikeman : Eliminates
object Knight{
status=1
}
Unit::Pikeman --> Knight : Eliminates
@enduml
